services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/g6B7jB_vMocVXQ13-6IKg7ax7dTNkNsOp8CrFkvanlw
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*,apoc.meta.*'
      NEO4J_dbms_security_procedures_allowlist: 'apoc.*,apoc.meta.*'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'